//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QLNen
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string CCCD { get; set; }
        public string Phone { get; set; }
        public string TenNen { get; set; }
        public string DienTich { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public string DiaChi { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
